package Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/* Người xây dựng: Lê Đức Mạnh*/
public class CanBoJFrame extends javax.swing.JFrame implements ActionListener{
    
    public static int maCbGlobal = 0;
    
    
    public CanBoJFrame() {
        initComponents();
        
        btnQuaTrinhCongTac.addActionListener(this);
        
        this.setLocationRelativeTo(null);
        setTitle("Thông Tin Cán Bộ Giáo Viên Trường Trung học cơ sở X - ĐỒ ÁN MÔN HỌC");
        showData(ConnectionSQL.findAllCanBo());
    }
    
public void showData(List<CanBo>canbol){
    if(canbol.size() == 0) System.out.println("Rỗng");
    List<CanBo>listCanBo = new ArrayList<>();
    listCanBo=canbol;
    DefaultTableModel tableModel;
    jTable.getModel();
    tableModel=(DefaultTableModel)jTable.getModel();
    tableModel.setRowCount(0);
    listCanBo.forEach((canbo) -> {
        tableModel.addRow(new Object[]{
            canbo.getMaCB(), canbo.getHoTen(), canbo.getSoDT(), canbo.getDiaChi(), canbo.getNamSinh(),
            canbo.getChucVu(), canbo.getSoTaiKhoan(), canbo.getBac()
    });
    });
            jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jTable.getSelectedRow() >= 0){
                    jtfMaCB.setText(jTable.getValueAt(jTable.getSelectedRow(), 0) + "");
                    jtfHoTen.setText(jTable.getValueAt(jTable.getSelectedRow(), 1) + "");
                    jtfSoDT.setText(jTable.getValueAt(jTable.getSelectedRow(), 2) + "");
                    jtfDiaChi.setText(jTable.getValueAt(jTable.getSelectedRow(), 3) + "");
                    jtfNamSinh.setText(jTable.getValueAt(jTable.getSelectedRow(), 4) + "");
                    jComboBox2.setSelectedItem(jTable.getValueAt(jTable.getSelectedRow(), 5) + "");
                    jtfSoTaiKhoan.setText(jTable.getValueAt(jTable.getSelectedRow(), 6) + "");
                    jComboBox1.setSelectedItem(jTable.getValueAt(jTable.getSelectedRow(), 7) + "");
                    maCbGlobal = Integer.parseInt(jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
//                  System.out.println("MaCB global co gia tri la: "+maCbGlobal);
                }
            }
        });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jtfNamSinh = new javax.swing.JTextField();
        jtfSoTaiKhoan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfMaCB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jtfHoTen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfSoDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnQuaTrinhCongTac = new javax.swing.JButton();
        btnLichSuLuong = new javax.swing.JButton();
        btnChiTietLuong = new javax.swing.JButton();
        btnLichSuLuongNgoaiGio = new javax.swing.JButton();
        btnChiTietLuongNgoaiGio = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1219, 660));

        jPanel1.setMaximumSize(new java.awt.Dimension(1219, 660));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Cán Bộ Giáo Viên trường THCS X");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edu.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eduhat.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Họ và Tên:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Địa Chỉ:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Năm Sinh:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Chức Vụ:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Số Tài Khoản:");

        jtfDiaChi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtfNamSinh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtfSoTaiKhoan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Mã Cán Bộ:");

        jtfMaCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));

        jTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Cán Bộ", "Họ và Tên", "Số Điện Thoại", "Địa Chỉ", "Năm Sinh", "Chức Vụ", "Số Tài Khoản", "Bậc Cán Bộ"
            }
        ));
        jTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTable);
        jTable.getAccessibleContext().setAccessibleName("");
        jTable.getAccessibleContext().setAccessibleDescription("");

        jtfHoTen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Số Điện Thoại");

        jtfSoDT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Bậc cán bộ:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bậc", "Bậc 1", "Bậc 2", "Bậc 3", "Bậc 4", "Bậc 5", "Bậc 6", "Bậc 7", "Bậc 8" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ", "Hiệu trưởng", "Hiệu phó", "Trưởng bộ môn", "Giáo viên bộ môn" }));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnQuaTrinhCongTac.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnQuaTrinhCongTac.setText("Quá trình công tác");
        btnQuaTrinhCongTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaTrinhCongTacActionPerformed(evt);
            }
        });
        jPanel3.add(btnQuaTrinhCongTac);

        btnLichSuLuong.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLichSuLuong.setText("Lịch sử lương");
        btnLichSuLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuLuongActionPerformed(evt);
            }
        });
        jPanel3.add(btnLichSuLuong);

        btnChiTietLuong.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChiTietLuong.setText("Chi tiết lương");
        jPanel3.add(btnChiTietLuong);

        btnLichSuLuongNgoaiGio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLichSuLuongNgoaiGio.setText("Lịch sử lương ngoài giờ");
        btnLichSuLuongNgoaiGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuLuongNgoaiGioActionPerformed(evt);
            }
        });
        jPanel3.add(btnLichSuLuongNgoaiGio);

        btnChiTietLuongNgoaiGio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChiTietLuongNgoaiGio.setText("Chi tiết lương ngoài giờ ");
        jPanel3.add(btnChiTietLuongNgoaiGio);

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRefresh.setText("Làm Mới");
        btnRefresh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDiaChi)
                                    .addComponent(jtfSoTaiKhoan)
                                    .addComponent(jtfNamSinh)
                                    .addComponent(jtfSoDT)
                                    .addComponent(jtfHoTen)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        CanBo st = new CanBo() {
        };
        st.setHoTen(jtfHoTen.getText());
        st.setChucVu(jComboBox2.getSelectedItem().toString());
        showData(ConnectionSQL.SearchCanBo(st));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        jtfMaCB.setText("");
        jtfHoTen.setText("");
        jtfDiaChi.setText("");
        jtfNamSinh.setText("");
        jtfSoDT.setText("");
        jtfSoTaiKhoan.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        showData(ConnectionSQL.findAllCanBo());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(jtfMaCB.getText().equals("") || jtfHoTen.getText().equals("") || jtfSoDT.getText().equals("") || jtfDiaChi.getText().equals("") ||
            jtfNamSinh.getText().equals("") || jComboBox2.getSelectedIndex() == 0 || jtfSoTaiKhoan.getText().equals("") || jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Hãy Nhập Đầy Đủ Dữ Liệu");
        } else{
            CanBo st = new CanBo() {
            };
            st.setMaCB(Integer.parseInt(jtfMaCB.getText()));
            st.setHoTen(jtfHoTen.getText());
            st.setSoDT(jtfSoDT.getText());
            st.setDiaChi(jtfDiaChi.getText());
            st.setNamSinh(jtfNamSinh.getText());
            st.setChucVu(jComboBox2.getSelectedItem().toString());
            st.setSoTaiKhoan(jtfSoTaiKhoan.getText());
            String str = jComboBox1.getSelectedItem().toString();
            if(str.equals("Bậc 1")) st.setBac(1);
            else if(str.equals("Bậc 2")) st.setBac(2);
            else if(str.equals("Bậc 3")) st.setBac(3);
            else if(str.equals("Bậc 4")) st.setBac(4);
            else if(str.equals("Bậc 5")) st.setBac(5);
            else if(str.equals("Bậc 6")) st.setBac(6);
            else if(str.equals("Bậc 7")) st.setBac(7);
            else if(str.equals("Bậc 8")) st.setBac(8);

            ConnectionSQL.UpdateCanBo(st);
            JOptionPane.showMessageDialog(null, "Cập Nhật Thành Công");
            showData(ConnectionSQL.findAllCanBo());}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CanBo st;
        st = new CanBo() {
        };
        st.setMaCB(Integer.parseInt(jtfMaCB.getText()));
        ConnectionSQL.DeleteCanBo(st);
        JOptionPane.showMessageDialog(null, "Xóa Dữ Liệu Thành Công");

        showData(ConnectionSQL.findAllCanBo());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(jtfMaCB.getText().equals("") || jtfHoTen.getText().equals("") || jtfSoDT.getText().equals("") || jtfDiaChi.getText().equals("") ||
            jtfNamSinh.getText().equals("") || jComboBox2.getSelectedIndex() == 0 || jtfSoTaiKhoan.getText().equals("") || jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Hãy Nhập Đầy Đủ Dữ Liệu");
        } else{
            CanBo st = new CanBo() {
            };
            st.setMaCB(Integer.parseInt(jtfMaCB.getText()));
            st.setHoTen(jtfHoTen.getText());
            st.setSoDT(jtfSoDT.getText());
            st.setDiaChi(jtfDiaChi.getText());
            st.setNamSinh(jtfNamSinh.getText());
            st.setChucVu(jComboBox2.getSelectedItem().toString());
            st.setSoTaiKhoan(jtfSoTaiKhoan.getText());
            String str = jComboBox1.getSelectedItem().toString();
            if(str.equals("Bậc 1")) st.setBac(1);
            else if(str.equals("Bậc 2")) st.setBac(2);
            else if(str.equals("Bậc 3")) st.setBac(3);
            else if(str.equals("Bậc 4")) st.setBac(4);
            else if(str.equals("Bậc 5")) st.setBac(5);
            else if(str.equals("Bậc 6")) st.setBac(6);
            else if(str.equals("Bậc 7")) st.setBac(7);
            else if(str.equals("Bậc 8")) st.setBac(8);
            else JOptionPane.showMessageDialog(null, "Hãy chọn đúng bậc của cán bộ giáo viên!!!!!");

            System.out.println("Cán bộ : MãCB: "+st.getMaCB() +" - Họ tên: "+st.getHoTen()+" - Số ĐT:"+st.getSoDT()+" - DiaChi: "+st.getDiaChi()+" - NamSinh: "+st.getNamSinh()+" - ChucVu: "+st.getChucVu()+" - SoTaiKhoan: "+st.getSoTaiKhoan()+"- Bac: "+st.getBac());

            ConnectionSQL.InsertCanBo(st);
            JOptionPane.showMessageDialog(null, "Thêm Mới Thành Công");
            showData(ConnectionSQL.findAllCanBo());}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLichSuLuongNgoaiGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuLuongNgoaiGioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLichSuLuongNgoaiGioActionPerformed

    private void btnLichSuLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLichSuLuongActionPerformed

    private void btnQuaTrinhCongTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaTrinhCongTacActionPerformed
        
    }//GEN-LAST:event_btnQuaTrinhCongTacActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanBoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanBoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanBoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanBoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CanBoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChiTietLuong;
    private javax.swing.JButton btnChiTietLuongNgoaiGio;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLichSuLuong;
    private javax.swing.JButton btnLichSuLuongNgoaiGio;
    private javax.swing.JButton btnQuaTrinhCongTac;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMaCB;
    private javax.swing.JTextField jtfNamSinh;
    private javax.swing.JTextField jtfSoDT;
    private javax.swing.JTextField jtfSoTaiKhoan;
    // End of variables declaration//GEN-END:variables

    
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnQuaTrinhCongTac)){
        btnQuaTrinhCongTacClick();
    }
//        else if(e.getSource().equals(btnLichSuLuong)){
//            btnLichSuLuongClick();
//        }
//        else if(e.getSource().equals(btnChiTietLuong)){
//            btnChiTietLuongClick();
//        }
//        else if(e.getSource().equals(btnLichSuLuongNgoaiGio)){
//            btnLichSuLuongNgoaiGioClick();
//        }
//        else if(e.getSource().equals(btnChiTietLuongNgoaiGio)){
//            btnChiTietLuongNgoaiGioClick();
//        }
    }
        
    public void btnQuaTrinhCongTacClick(){
        new QuaTrinhCongTacMotCBJFrame().setVisible(true);
    }
    
//    public void btnQuaTrinhCongTacClick(){
//        new QuaTrinhCongTacMotCBJFrame().setVisible(true);
//    }
//    
//    public void btnQuaTrinhCongTacClick(){
//        new QuaTrinhCongTacMotCBJFrame().setVisible(true);
//    }
//    
//    public void btnQuaTrinhCongTacClick(){
//        new QuaTrinhCongTacMotCBJFrame().setVisible(true);
//    }
//    
//    public void btnQuaTrinhCongTacClick(){
//        new QuaTrinhCongTacMotCBJFrame().setVisible(true);
//    }
}